### ISSUE TITLE
[EPIC][Community Ownership][QA] Flows for sending owner token 

### ISSUE THREAD

**Issue by glitchminer** [status-im/desktop-qa-automation#132]
### Description

- Figma: https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=37206-87272&mode=design&t=FMXiXok3OsKx0yAZ-4

- Dev issues:
UI epic https://github.com/status-im/status-desktop/issues/12087
AND
backend epic https://github.com/status-im/status-desktop/issues/11370

### Tasks

- [ ] Create e2e happy paths based on Figma
- [ ] Create Negative scenarios
- [ ] Execute happy paths, minimum
- [ ] Create automation tasks in backlog

### Test summary

Description of tests and results.

#### Initiate flow from
| Scenario | State | Notes |
|--------|--------|--------|
| Wallet | TR Prep | |
| Token settings screen | TR Prep | |
| Community overview | TR Prep | | 

#### Send owner token

| Scenario | State | Notes |
|--------|--------|--------|
| Send owner token | TR Prep | |

#### Receive owner token

**Initiate finalisation** 
| Scenario | State | Notes |
|--------|--------|--------|
| Notification centre | TR Prep | |
| Community | TR Prep | |
| Community admin dialog as Admin/TM | TR Prep | |
| Community admin footer button as Admin/TM | TR Prep | |

**Perform finalisation**
| Scenario | State | Notes |
|--------|--------|--------|
| As existing Admin, TM or Member with sufficient funds | TR Prep | |
| As a non-member with sufficient funds  | TR Prep | |
| With insufficient funds | TR Prep | |
| As existing Admin, TM or Member declining ownership  | TR Prep | |
| As a non-member declining ownership  | TR Prep | |
| Return token to sender toast | TR Prep | |

**Move control node flow**
| Scenario | State | Notes |
|--------|--------|--------|
| Move control node via community admin | Not started | |
| Control node transition screen | Not started | |

**Errors**
| Scenario | State | Notes |
|--------|--------|--------|
| Smart contract failure | Not started | |
| Relaunch finalisation | Not started | |

**Comment by noeliaSD** [comment]
The UI epic is dependent on the backend one: https://github.com/status-im/status-desktop/issues/11370
- Integration is missing.
- `Storybook` incorporates all new components used in the app so they can be tested in isolation.
