### ISSUE TITLE
[EPIC][Discord import][QA] Discord history import into a single channel in an existing community

### ISSUE THREAD

**Issue by glitchminer** [status-im/desktop-qa-automation#133]
### Description

- Dev issues:
Epic https://github.com/status-im/status-desktop/issues/12018

### Tasks

- [ ] Create e2e happy paths based on Figma
- https://ethstatus.testrail.net/index.php?/suites/view/5308&group_id=51505
- [ ] Create Negative scenarios
- [ ] Execute happy paths, minimum
- [ ] Create automation tasks in backlog

### Test summary

Description of tests and results

**Comment by anastasiyaig** [comment]
dev task was moved to 0.17
