### ISSUE TITLE
[EPIC][Community Directory][QA] Get Deploy Community Directory Curation dApp deployed

### ISSUE THREAD

**Issue by glitchminer** [status-im/desktop-qa-automation#135]
### Description

- Dev issues
 epic https://github.com/status-im/status-desktop/issues/11461

status-desktop should reflect the state of the DApp:
if testnet is enabled it should reflect: https://community-dapp-git-review-status-im-web.vercel.app/directory
if testnet is not enabled it should reflect: https://curate.status.app/directory

https://status.app/help/communities/about-voting-to-change-the-community-visibility
https://status.app/help/communities/vote-to-make-a-community-private-or-public
https://status.app/help/communities/vote-to-feature-a-status-community

### Tasks

- [ ] Create e2e happy paths based on Figma
- [ ] Create Negative scenarios
- [ ] Execute happy paths, minimum
- [ ] Create automation tasks in backlog

### Test summary

Description of tests and results

**Comment by anastasiyaig** [comment]
That is still to be covered, however i cant find any relevant docs now. I will update everything when i have correct links on how it supposed to work

**Comment by anastasiyaig** [comment]
UPD: found them and replaced in the desc

**Comment by anastasiyaig** [comment]
https://status.app/help/communities as a general source

**Comment by anastasiyaig** [comment]
@glitchminer pls review the coverage in test rail for this and update if possible , then this story can be closed. thank u

**Comment by glitchminer** [comment]
Scenarios in test rail are needed. Started making notes for this locally. Also reviewing whether a retest is needed.

**Comment by glitchminer** [comment]
Added primary cases to Community portal and discovery.
