### ISSUE TITLE
[Test] Handle right click - close application scenario

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#155]
To cover this https://github.com/status-im/status-desktop/issues/12383

Squish article: https://kb.froglogic.com/squish/qt/howto/tray-icons/

**Comment by Valentina1133** [comment]
`I already created PR for this task, it's under review - https://github.com/status-im/desktop-qa-automation/pull/432 
There is also the issue during test run for PR - I was tying to find a reason but no success, so I also asked Nastya to check it when she has time https://ci.status.im/job/status-desktop/job/qa-automation/job/prs/job/PR-432/6/display/redirect`
