### ISSUE TITLE
[Test] Tests in old framework to move to Pytest framework

### ISSUE THREAD

**Issue by Valentina1133** [status-im/desktop-qa-automation#171]
I reviewed old framework tests and here is a list of tests to move to a new framework. Maybe I missed smth, so feel free to add more if needed

Settings suite
- Language settings
- Sign up and quit

Communities suite
- Manage airdrop + 
- Manage Mint tokens +
- Admin can delete another member's message
- Member flows
- Message flows - in progress
- Search flows

**Comment by anastasiyaig** [comment]
Communities suite should be reworked completely. For now we need at least to test the community creation on CI , which is now not working. Once we fix that, someone will provide more valid scenarios for communities to cover

Search is not important for now, settings are being reworked just now

My concern is messaging but we need to get back to it with proper coverage, and i believe that should be done within communities tests.

I am closing that as completed, perhaps we will add some more tasks later on before dropping old framework completely
