### ISSUE TITLE
Can't navigate / see OpenFileDialog on Linux-03

### ISSUE THREAD

**Issue by StateOf-Vlado** [status-im/desktop-qa-automation#218]
**Steps:**

1. Start job https://ci.status.im/job/status-desktop/job/e2e/job/manual/ with parameters:
- GIT_REF: **chore/218**
- BUILD_SOURCE: any or https://status-im-nightlies.ams3.digitaloceanspaces.com/StatusIm-Desktop-231030-035700-fd0e4e-nightly-x86_64.tar.gz
- TEST_NAME: test_create_community
- AGENT: linux-3
2. Open the Allure report
3. Open report for test_create_community
4. Open 'Test body' overview
5. Open 'Set community logo' step

**Expected result:**
The step 'Set community logo' pass
**Actual result:**
The step 'Set community logo' failed with error:
```LookupError: Object '{container='{container=\'{title=\\\'Choose an image as logo\\\' type=\\\'QQuickWindow\\\' unnamed=\\\'1\\\' visible=\\\'true\\\'}\' id=\'titleBar\' type=\'ToolBar\' unnamed=\'1\' visible=\'true\'}' id='currentPathField' type='TextField' unnamed='1' visible='true'}' not ready: Quick item is outside rendered area```

Screenshot on fail:
![Image](https://github.com/status-im/desktop-qa-automation/assets/128374224/4509a7ae-2fcf-47d2-b4a2-afb41dcc28da)

In console output:
```
09:54:52  08:54:46.080    INFO gui.elements.object  Button(addButton_StatusRoundButton2): clicked
09:54:52  08:54:46.081    INFO gui.elements.button  Button(addButton_StatusRoundButton2): clicked
09:54:52  08:54:46.197    INFO gui.elements.object  OpenFileDialog(chooseAnImageALogo_QQuickWindow): is visible
09:54:52  08:54:46.201    INFO gui.elements.window  Window Choose an image as logo appears
```
Choose an image as logo is hidden

**Comment by yakimant** [comment]
@StateOf-Vlado, @anastasiyaig, @jakubgs,
we can temporary exclude linux-03 from the list.

For example by adding a lable 'desktop-e2e' to all but linux-03 and add it to requirements:
https://github.com/status-im/desktop-qa-automation/blob/4e918fe901c3623f750b3affa1e42439811d46d8/ci/Jenkinsfile#L7

**Comment by jakubgs** [comment]
Please lets not create custom labels just for one specific purpose. If a host has issues it should be disabled for given desktop runs, by for example temporarily renaming `qt-5.15.2` to `qt-5.15.2-DISABLED`.

Also, why does the log message say `Window Choose an image as logo appears`, the key word here being `appears`, when you say it's hidden? Is this just a badly phrased log message or is this issue a red herring?

**Comment by StateOf-Vlado** [comment]
@jakubgs , maybe you forgot, but previously when we set up the environment, we found that dialog can be found by Squish, but it is not visible. There was a log with coordinates like x=0, y=0, height =0, and width =0. Do you remember it? If you need logs again, I can add them.

**Comment by yakimant** [comment]
Changed the label manually, so tests should not run anymore on linux-03

**Comment by jakubgs** [comment]
Thanks. Hmmm, didn't we fix it last time by starting a window manager?

**Comment by jakubgs** [comment]
I collected lists of packages installed on `linux-01`, `linux-02` and `linux-03` using `apt list --installed` and compared them.

Here's some major differences I found:
```
 > diff linux-01_apt.list linux-03_apt.list | grep '^<' | wc -l
284
 > diff linux-02_apt.list linux-03_apt.list | grep '^<' | wc -l
186
```

**Comment by jakubgs** [comment]
As we can see here `linux-01` and `linux-02` have Xorg server installed:
```
 > diff linux-01_apt.list linux-03_apt.list | grep '^<' | grep xorg
< xorg-docs-core/jammy,jammy,now 1:1.7.1-1.2 all [installed,auto-removable]
< xorg/jammy,jammy,now 1:7.7+23ubuntu2 amd64 [installed,auto-removable]
< xserver-xorg-core/jammy-updates,jammy-updates,now 2:21.1.4-2ubuntu1.7~22.04.1 amd64 [installed,automatic]
< xserver-xorg-input-all/jammy,jammy,now 1:7.7+23ubuntu2 amd64 [installed,automatic]
< xserver-xorg-input-libinput/jammy,jammy,now 1.2.1-1 amd64 [installed,automatic]
< xserver-xorg/jammy,jammy,now 1:7.7+23ubuntu2 amd64 [installed,automatic]

 > diff linux-02_apt.list linux-03_apt.list | grep '^<' | grep xorg
< xorg-docs-core/jammy,jammy,now 1:1.7.1-1.2 all [installed,automatic]
< xserver-xorg-core/jammy-updates,jammy-updates,now 2:21.1.4-2ubuntu1.7~22.04.1 amd64 [installed,automatic]
< xserver-xorg-input-all/jammy,jammy,now 1:7.7+23ubuntu2 amd64 [installed,automatic]
< xserver-xorg-input-libinput/jammy,jammy,now 1.2.1-1 amd64 [installed,automatic]
< xserver-xorg/jammy,jammy,now 1:7.7+23ubuntu2 amd64 [installed,automatic]
```
But `linux-04` doesn't, as as far as we know it works without issues.
```
 > diff linux-04_apt.list linux-03_apt.list | grep '^<' | grep xorg

```

**Comment by jakubgs** [comment]
If compared against `linux-04` after running upgrades I don't see any major differences:
```
 > diff linux-04_apt.list linux-03_apt.list | grep '^<'
< Listing...
< gnupg2
< libpcre32-3
< linux-image-5.15.0-87-generic
< linux-modules-5.15.0-87-generic
< linux-modules-extra-5.15.0-87-generic
< ruby
```

**Comment by jakubgs** [comment]
I used these commands on `linux-03`:
```
Xvfb :2 -screen 0 1680x1050x24&
fluxbox &
zenity --file-selection &
import -window root screenshot.png
```
And `zenity` file selector opens without issues:

![screenshot](https://github.com/status-im/desktop-qa-automation/assets/2212681/e2b281b6-4584-432b-af66-eccee5637b1d)

**Comment by jakubgs** [comment]
The best way to debug this would be to have a tiny program that starts a file open dialog the same way our app does it.

**Comment by jakubgs** [comment]
I found this:
```nim
            function chooseImageToCrop() {
                fileDialog.open()
            }
```
https://github.com/status-im/status-desktop/blob/99c113c82901c94e662953f3c5c0d821d1ef2003/ui/StatusQ/sandbox/pages/StatusImageCropPanelPage.qml#L170-L172

**Comment by jakubgs** [comment]
Or not, linux version just calls `zenity`:
```c
  n = sprintf(buf, "zenity --file-selection");
```
https://github.com/rxi/sfd/blob/7d83fe9577f2d4bfe74e7b08d25e3c7ad644d49d/src/sfd.c#L190

**Comment by jakubgs** [comment]
I found this example, but compiling it is no trivial matter if you don't know what you're doing:
http://www.codebind.com/cpp-tutorial/qt-tutorial/qt-tutorials-beginners-qfiledialog-getopenfilename-example/

**Comment by jakubgs** [comment]
I ran a manual job on the `linux-03` host an it worked: https://ci.status.im/job/status-desktop/job/e2e/job/manual/783/

The only things I really did on the host was:

1. Run `apt upgrade` and reboot the host.
2. `qapt reinstall nautilus` - Just a hunch.
3. `qapt install xvfb-run xwud x11-apps zenity` - For debugging.

Pretty sure nothing else was done on the host that's relevant.

**Comment by jakubgs** [comment]
Stefan helped me out by creating this change that allows the storybook to open the file dialog at startup:
```diff
From ea859fdae6ed1ae7da63d94fdf571c7cb7834a7e Mon Sep 17 00:00:00 2001
From: Stefan <stefand@status.im>
Date: Thu, 2 Nov 2023 22:39:29 +0200
Subject: [PATCH] Debug file dialog in storybook

---
 storybook/main.qml                           | 4 ++--
 storybook/pages/StatusImageCropPanelPage.qml | 4 ++++
 2 files changed, 6 insertions(+), 2 deletions(-)

diff --git a/storybook/main.qml b/storybook/main.qml
index 2598d57df6e..bcfc9692f62 100644
--- a/storybook/main.qml
+++ b/storybook/main.qml
@@ -19,7 +19,7 @@ ApplicationWindow {
     height: 840
     visible: true
 
-    property string currentPage
+    property string currentPage: "StatusImageCropPanel"
 
     title: "%1 – %2".arg(currentPage).arg(Qt.application.displayName)
 
@@ -354,7 +354,7 @@ Tips:
     Settings {
         id: settings
 
-        property alias currentPage: root.currentPage
+        //property alias currentPage: root.currentPage
         property alias loadAsynchronously: settingsLayout.loadAsynchronously
         property alias runTestsAutomatically: settingsLayout.runTestsAutomatically
         property alias darkMode: darkModeCheckBox.checked
diff --git a/storybook/pages/StatusImageCropPanelPage.qml b/storybook/pages/StatusImageCropPanelPage.qml
index 60cd75bb3b7..2b2c0fa1bfd 100644
--- a/storybook/pages/StatusImageCropPanelPage.qml
+++ b/storybook/pages/StatusImageCropPanelPage.qml
@@ -28,6 +28,10 @@ SplitView {
     implicitWidth: mainLayout.implicitWidth
     implicitHeight: mainLayout.implicitHeight
 
+    Component.onCompleted: {
+        workflowLoader.active = true
+    }
+
     Logs { id: logs }
 
     SplitView {
```
https://github.com/status-im/status-desktop/tree/debug_file_dialog

Apparently it can be tested with:
```
cmake -B ./storybook/build/ -S storybook
cmake --build storybook/build/
storybook/build/bin/Storybook
```
Will test tomorrow.

**Comment by anastasiyaig** [comment]
@jakubgs ping me when testing this, i will assist with enabling tests that were dependent on the file dialog, because now they are off

**Comment by anastasiyaig** [comment]
@jakubgs i ran it today with the branch `chore/debug_community`: https://ci.status.im/job/status-desktop/job/e2e/job/manual/784/console

```
FAILED tests/communities/test_communities.py::test_create_community[params0] - LookupError: Object '{container='{container=\'{title=\\\'Choose an image as logo\\\' type=\\\'QQuickWindow\\\' unnamed=\\\'1\\\' visible=\\\'true\\\'}\' id=\'titleBar\' type=\'ToolBar\' unnamed=\'1\' visible=\'true\'}' id='currentPathField' type='TextField' unnamed='1' visible='true'}' not ready: Quick item is outside rendered area
```

Test stays on this screen and seem to be unable to either open or navigate to opened file upload dialog

![image](https://github.com/status-im/desktop-qa-automation/assets/82375995/3d4fab70-4144-4b10-8d5e-76c72bddfefc)

**Comment by jakubgs** [comment]
I see, you used `chore/debug_community` branch and `test_create_community` for test name, thanks.

**Comment by stefandunca** [comment]
Looking at the documentation of [FileDialog](https://doc.qt.io/qt-5/qml-qtquick-dialogs-filedialog.html#details), it seems two fallback backend implementations could go wrong. It looks like the combination of window manager and available APIs might have triggered a corner case fail in Qt (which is usually seen in the logs)

From the [docs](https://doc.qt.io/qt-5/qml-qtquick-dialogs-filedialog.html#details):
"The implementation of FileDialog will be a platform file dialogue **if possible**. If that **isn't possible**, then it will try to instantiate a [QFileDialog](https://doc.qt.io/qt-5/qfiledialog.html). If that also **isn't possible**, then it will fall back to a QML implementation, DefaultFileDialog.qml. ..."

Debugging:
- switching the file manager might help avoid the buggy implementation.
- running with verbose logs by exporting `QT_LOGGING_RULES="*.debug=true"`

**Comment by jakubgs** [comment]
I've built and ran the `debug_file_dialog` branch using:
```sh
git clone https://github.com/status-im/status-desktop.git --branch debug_file_dialog
cd status-desktop
export QTDIR="/opt/qt/5.15.2/gcc_64"
export PATH="${QTDIR}/bin:${PATH}"
make update
cmake -B ./storybook/build/ -S storybook
cmake --build storybook/build/
storybook/build/bin/Storybook
```
And it does open the dialog just fine:

![image](https://github.com/status-im/desktop-qa-automation/assets/2212681/93c81b61-4911-444b-a0bb-3268239e31d5)

**Comment by jakubgs** [comment]
I downloaded the most recent nightly builds AppImage and it appears to work fine:

![image](https://github.com/status-im/desktop-qa-automation/assets/2212681/d0be4d1d-7ab2-4a7a-a8d4-f91ae36afa0c)

I don't see any issues. Can't reproduce it.

**Comment by jakubgs** [comment]
Just in case I tested as `jenkins` user, and it works fine, here's `xprop` output for the file dialog:

![image](https://github.com/status-im/desktop-qa-automation/assets/2212681/5396fb5c-6428-450a-927c-3e4ead8144da)

I consider this issue to be gone, and will re-add the host to CI queue.

**Comment by jakubgs** [comment]
I might add that I saw no clear lag when interacting with the app over VNC, so I don't think Xvfb causes performance issues.

**Comment by anastasiyaig** [comment]
lets bring this host back @jakubgs

**Comment by stefandunca** [comment]
> Managed to get a VNC session going on `linux-03` host using the following command:
> 
> ```shell
> x11vnc -create \
>   -env "FD_PROG=/usr/bin/fluxbox" \
>   -env "X11VNC_FINDDISPLAY_ALWAYS_FAILS=1" \
>   -env "X11VNC_CREATE_GEOM=${1:-1024x768x16}" \
>   -gone "killall Xvfb" \
>   -bg -nopw
> ```

Thanks for the info
