### ISSUE TITLE
[EPIC][Wallet][QA] Send NFT

### ISSUE THREAD

**Issue by glitchminer** [status-im/desktop-qa-automation#246]
QA for https://github.com/status-im/status-desktop/issues/11953

### Description:
send NFT using the send modal

**Dev tasks:**

https://github.com/status-im/status-desktop/issues/12072
https://github.com/status-im/status-desktop/issues/12095
https://github.com/status-im/status-desktop/issues/12128

**Figma**

https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=13540-381042&mode=design

https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=16937-300216&mode=design&t=BGSvPYlkRk2qPSZs-0

**Tasks**

- [ ] Create e2e happy paths based on Figma
https://ethstatus.testrail.net/index.php?/cases/view/704602
- [ ] Create Negative scenarios
- [ ] Execute happy paths, minimum
- [ ] Create automation tasks in backlog
- https://github.com/status-im/desktop-qa-automation/issues/295

**Bugs / leftovers**

- https://github.com/status-im/status-desktop/issues/12734
- https://github.com/status-im/status-desktop/issues/12689

**Comment by anastasiyaig** [comment]
I am closing this as done now
