### ISSUE TITLE
Add a trigger for new-tests against the PRs in qa-automation repo

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#254]
I need the tests to be launched within PRs I create in qa-automation repository. 
This action should go to GitHub actions checklist (not mandatory to pass for now)
For now, lets execute all tests based on the branch from PR

**Comment by jakubgs** [comment]
Okay, but what kind of Desktop build should be used? Latest nightly?

**Comment by anastasiyaig** [comment]
sorry i forgot to mention, yes lets try latest nightly

**Comment by jakubgs** [comment]
Here are the changes:

* https://github.com/status-im/status-desktop/pull/12643
* https://github.com/status-im/desktop-qa-automation/pull/270

**Comment by jakubgs** [comment]
One weird behavior is that the default for `BUILD_SOURCE` doesn't naturally take effect for already existing PRs.

The solution is to rebase, push, and then run a manual build with `BUILD_SOURCE=status-desktop/nightly`.

**Comment by jakubgs** [comment]
Yeah, we could have a job. I wonder how this ties into:

* https://github.com/waku-org/nwaku/issues/2107

**Comment by jakubgs** [comment]
Here's an improvement to build names:

* https://github.com/status-im/desktop-qa-automation/pull/279

Since I kinda broke desktop PR build names with last PR.
