### ISSUE TITLE
UI tests: Can do a token transfer in testnet

### ISSUE THREAD

**Issue by iurimatias** [status-im/desktop-qa-automation#26]

**Comment by Valentina1133** [comment]
All changes are in branch test/test_sending_nft 

I stuck at the step when it should choose STT and then enter amount. The step passes in autotest but actually it's not chosen so then test fails for entering amount.

I tried many things here - findallobjects, walk_children, using indexes for choosing STT. Nothing worked. It either passes but actually not, or (when I used index) it chooses wrong asset - DAI, although it's index for STT in Squish.  

So I also asked Nastya to check it maybe she will have more ideas what we can do here.

**Comment by anastasiyaig** [comment]
I will take a look , sure. 

Meanwhile, it is dependant on https://github.com/status-im/desktop-qa-automation/issues/445
