### ISSUE TITLE
Create screenshot of multiple instances on failed test

### ISSUE THREAD

**Issue by StateOf-Vlado** [status-im/desktop-qa-automation#271]
- Set the window visible
- Grab screenschot
- Attach to allure report

**Comment by anastasiyaig** [comment]
@StateOf-Vlado i am not entirely sure. Why this task appeared and why it took higher priority than others?

**Comment by StateOf-Vlado** [comment]
I see that we don't have a screenshot on the failed PR's test results
To Identify issues in PR's we have to see what is happening.

**Comment by anastasiyaig** [comment]
alright but that would not get higher priority than other tasks that have been already prioritized for you
