### ISSUE TITLE
Fix test_create_keycard_account_with_new_seed_phrase on CI

### ISSUE THREAD

**Issue by squ1sher** [status-im/desktop-qa-automation#274]
https://ci.status.im/job/status-desktop/job/e2e/job/manual/800/allure/#suites/0f77a6f183d066f8c445faa62d52d1c8/7c720904ce958ec9/

![Image](https://github.com/status-im/desktop-qa-automation/assets/128374224/82893af9-0e1a-4d9a-bb9f-fdaab6eac087)

**Comment by anastasiyaig** [comment]
probably depends on https://github.com/status-im/desktop-qa-automation/issues/278

**Comment by anastasiyaig** [comment]
it should be retested after we switch to 5.15.8 on CI https://github.com/status-im/status-desktop/pull/9232

**Comment by Valentina1133** [comment]
It works fine, issue disappeared - tested here https://github.com/status-im/desktop-qa-automation/issues/574. 
But we don't enable test mode yet
