### ISSUE TITLE
Investigate connection timed out and handshake timeout errors in nightly

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#277]
There are 2 problems in last nightly run https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/41/allure/#suites/a23b444aafd0c8271b17f185e4eb34a2/310a3fa7fa55b03c/

https://ci.status.im/job/status-desktop/job/nightly/41/

`AssertionError: Could not connect to Squish server at host 127.0.0.1, port 4363: Connection timed out `
and
`AssertionError: Timeout expired during handshake`

Please check it out, why we have those

**Comment by StateOf-Vlado** [comment]
Resolver via starting AUT with squish.startApplication method
But I have to test solution on Linux locally, tests on CI stuck after Onboarding

**Comment by anastasiyaig** [comment]
sure @StateOf-Vlado , we definitely need linux for you. Hope u can set it up quickly and debug

**Comment by anastasiyaig** [comment]
reproduced today as well https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/90/allure/#suites/17f9cc57f67e22bcd8ed30a97930de7f/506c567ab3598a12/

**Comment by anastasiyaig** [comment]
@StateOf-Vlado please add me and Noelia to this email chain

**Comment by anastasiyaig** [comment]
The problem was that the application was crashing on close. It is fixed in https://github.com/status-im/status-desktop/pull/12881. This is the test run i launched in the branch https://ci.status.im/job/status-desktop/job/e2e/job/manual/1124/allure/#suites/4516d92a77da5a21d6cc36335b5a380f/8621a5de2989eee9/

- no timeouts 
- no ERROR records in logs

There is still problem that the framework does not provide anything meaningful when the app is crashed (no logs from app, no logs from squishserver) and the other problem is that the test execution is not stopped when this happens, so we have extra delays and wasted time

https://github.com/status-im/status-desktop/issues/12816#issuecomment-1827839389

**Comment by anastasiyaig** [comment]
closing that, have not seen this errors yet after refactoring
