### ISSUE TITLE
[Tests] Send messages with link previews

### ISSUE THREAD

**Issue by lukaszso** [status-im/desktop-qa-automation#281]
Add tests so we can cover https://github.com/status-im/desktop-qa-automation/issues/130

Test cases to be automated:
- https://ethstatus.testrail.net/index.php?/cases/view/704596
- https://ethstatus.testrail.net/index.php?/cases/view/704578
- https://ethstatus.testrail.net/index.php?/cases/view/704589

**Comment by anastasiyaig** [comment]
@lukaszso if possible, can we divide this task into 2 ? The most critical ones can be automated first class and perhaps will go in 0.15.5 even, the rest would be for 0.16

**Comment by lukaszso** [comment]
@anastasiyaig you're right, it was a bit too much :)  i've reduced it to the most cirtical cases.

**Comment by anastasiyaig** [comment]
perfect! thanks a ton

**Comment by Valentina1133** [comment]
It's ready. But I will create PR later, because of repository migration
