### ISSUE TITLE
Fix community tests

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#283]
```12:58:14  09:58:13.853    INFO gui.elements.text_edit  TextEdit(createCommunityOutroMessageInput_TextEdit): value changed to "5SW7fdcdy9g4OLZs5XE4nczlpOGecqFHjPEfJD7cGog5sUi4xF7GvbuIxwWF1iYbF5Z3JdenbsniBTkN"
12:58:14  09:58:14.817    INFO gui.elements.object  Button(createCommunityFinalBtn_StatusButton): clicked
12:58:14  09:58:14.818    INFO gui.elements.button  Button(createCommunityFinalBtn_StatusButton): clicked
```

community creation gets stuck on this screen. Tried Linux 01, 02, 05

![Image](https://github.com/status-im/desktop-qa-automation/assets/82375995/9af92767-0db7-4516-84ed-e152097d0ec0)

**Comment by StateOf-Vlado** [comment]
I found that the test becomes frozen if some elements are not found, like squish.waitForObject
So, here, we can add just an additional attempt to click the Create button to avoid this issue.

**Comment by anastasiyaig** [comment]
thats what i thought! I think i added it today for a try, but will do another attempt tomorrow

**Comment by anastasiyaig** [comment]
The task is renamed to more general one, to track the efforts of fixing communities overall tests

**Comment by anastasiyaig** [comment]
Issue is still there, see comment https://github.com/status-im/desktop-qa-automation/pull/327#issuecomment-1822715848
