### ISSUE TITLE
UI tests: cover sending NFT from send modal scenario

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#295]
Automate https://ethstatus.testrail.net/index.php?/cases/view/704602

NFT faucet: https://status-im.github.io/nft-faucet/mint

**Comment by anastasiyaig** [comment]
why it was closed :D

**Comment by Valentina1133** [comment]
It's pause because we were not able to generate many collectibles, so I had one and it's already gone during first attempt to run test. Need more collectibles (but I cannot generate them as services don't work for me in Russia)

**Comment by anastasiyaig** [comment]
We can pause that for now (but please keep the branch! ) . It anyway should wait for https://github.com/status-im/desktop-qa-automation/issues/445

**Comment by anastasiyaig** [comment]
@Valentina1133 lets get back to that one, i posted the link to NFT faucet which can be used to mint collectibles

**Comment by anastasiyaig** [comment]
already implemented
