### ISSUE TITLE
Wallet - Settings: cover missing scenarios for Account View actions

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#300]
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=18442-516604&mode=design&t=4sjoRSJg3p9IYabY-4

Actions with kebab menu and on-hovering

**Comment by Michal-Status** [comment]
Test cases can be found here: https://ethstatus.testrail.net/index.php?/suites/view/5308&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=51500
