### ISSUE TITLE
Test Set up keycard and login after restart using keycard

### ISSUE THREAD

**Issue by Valentina1133** [status-im/desktop-qa-automation#319]
I checked Sale's presentation again and found a way to automate login with a keycard (need to use custom seed phrase for sign up, then set up keycard with existing account and then restart the app and log in with keycard)

**Comment by Valentina1133** [comment]
There are different scenarios after start of restoring account with seed phrase. Sometimes it takes 2 minutes, then Unable to fetch window appears, sometimes button Continue get enabled almost right away. So scenarios are completely different and for now I don't have an idea how to handle it. So for now leave this task open and will switch to smth else

**Comment by Valentina1133** [comment]
As we discussed with Nastya - this issue will be in backlog for a while because we don't know yet how to deal with different behaviour after restore

**Comment by anastasiyaig** [comment]
Ya, we need to think of how to handle the waku restore thing indeed. I will think about it a bit later :)
