### ISSUE TITLE
Handle slow app rendering when in TEST_MODE (or having xvfb as a guess)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#323]
https://ci.status.im/job/status-desktop/job/e2e/job/manual/974/allure/#suites/02c42b923c11bb8717a016c430995276/7a6541357be7b51b/

![image](https://github.com/status-im/desktop-qa-automation/assets/82375995/db27090f-cc02-43b0-bf1b-c8b3f47d8380)

**Comment by anastasiyaig** [comment]
A wild guess could be the xvfb causing the slow render https://minerl.readthedocs.io/en/latest/notes/performance-tips.html

**Comment by jakubgs** [comment]
It's possible to VNC into an Xvfb instance if it's running a VNC server to see how the app behaves locally:
https://stackoverflow.com/questions/12050021/how-to-make-xvfb-display-visible

**Comment by anastasiyaig** [comment]
i disabled keycard mock to reduce the impact.
I will test the tests with TEST MODE enabled and disabled.

i noticed that this render issue happens with TEST MODE enabled.

on other hand , having the test mode disabled leads to some tests timing out because of Squish server connection error.

I will post here the findings

**Comment by anastasiyaig** [comment]
The problem with screens appearing slow with test mode is still there. However, calling it as a slow rendering perhaps is not correct and is misleading. To be honest, i dont yet know what is it

![image](https://github.com/status-im/desktop-qa-automation/assets/82375995/a293c071-89c1-4831-a32e-6c9234eb31b4)

**Comment by jakubgs** [comment]
I can see Settings load from current nightly without any issues or lag over `x11vnc` on `linux-03` CI host:

![image](https://github.com/status-im/desktop-qa-automation/assets/2212681/43be7362-bbee-4383-b8f5-9cde58d8ba60)

Does it not load fully for you? Where?

**Comment by anastasiyaig** [comment]
@jakubgs ah, in nightly we run without TEST_MODE now. I can launch a manual run with TEST MODE = ON to see what is happening, also, perhaps u can add a env var to that host and try manually? clicking through random settings screens with STATUS_RUNTIME_TEST_MODE = true?

**Comment by jakubgs** [comment]
It starts in test mode without issues, the `Lib Controller` is in focus first:

![image](https://github.com/status-im/desktop-qa-automation/assets/2212681/cddce0e9-3586-4e5b-81d3-57983a079aef)

**Comment by jakubgs** [comment]
Loading settings is fast, though rendering for a split second is kinda wonky:

![image](https://github.com/status-im/desktop-qa-automation/assets/2212681/dba5b9e4-946b-4ebb-9f01-a76060d15f1b)

**Comment by jakubgs** [comment]
One weird thing is, when I closed the process using the window title bar `X` button the process didn't exit, it's still running.

That's weird.

**Comment by jakubgs** [comment]
I can stop the process in the console using `ctrl+c`:
```
^CTraceback (most recent call last)
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/nim_status_client.nim(208) nim_status_client
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/nim_status_client.nim(205) mainProc
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec
SIGINT: Interrupted by Ctrl-C.

admin@linux-03.he-eu-hel1.ci.devel:~ % 
```
But that doesn't seem like normal behavior to me.

**Comment by anastasiyaig** [comment]
I was able to reproduce the issues with slow render on my machine. Nothing to do with xvfb, in fact it is old QT version 5.15.2
I need https://github.com/status-im/status-desktop/pull/9232 to retest with newer QT, and i am pretty confident the issue will be gone
