### ISSUE TITLE
Handle keycard window properly

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#324]
Sometimes tests fail perhaps because of it

https://ci.status.im/job/status-desktop/job/e2e/job/manual/974/allure/#suites/1e36570682c3d0323c63dbeef5e49edf/9e8d1db3332572c9/

![image](https://github.com/status-im/desktop-qa-automation/assets/82375995/b9a4a127-f2a4-4353-a2bc-23828885168e)

**Comment by anastasiyaig** [comment]
@StateOf-Vlado please fix the cases when we have ` AssertionError: Object UserCanvas(o_StatusListView) is not visible`

https://ci.status.im/job/status-desktop/job/qa-automation/job/prs/job/PR-327/1/allure/#suites/8e392deae3ddbc9e03b45d214f2f6e0a/235bbee7ea666de2/

**Comment by StateOf-Vlado** [comment]
You need to set TEST_MODE parameter correctly
https://github.com/status-im/desktop-qa-automation/blob/6f22ff6f80e0a394a042fb2895487ed864ee70db/configs/system.py#L12

If we use a string value like "0", we can not use it in case: `if TEST_MODE: do_something()`

**Comment by anastasiyaig** [comment]
I found out that there is another problem: on linux with STATUS_RINTIME_TEST_MODE = True sometimes test is not able to open online identifier. I am closing this task as it is totally other problem
