### ISSUE TITLE
Syncing test fails with AttributeError: 'NoneType' object has no attribute 'attach'

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#350]
```AttributeError: 'NoneType' object has no attribute 'attach'
  File "/home/jenkins/workspace/status-desktop/e2e/manual/tests/onboarding/test_onboarding_syncing.py", line 42, in test_sync_device_during_onboarding
    aut_one.attach()
```
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1177/allure/#suites/8e392deae3ddbc9e03b45d214f2f6e0a/5e3b3926aabee73/

<img width="1840" alt="Screenshot 2023-11-30 at 12 03 24" src="https://github.com/status-im/desktop-qa-automation/assets/82375995/db5a165e-c7c4-4545-873a-a1ded24b8197">

**Comment by Valentina1133** [comment]
I removed mark and ran locally - all was good. On CI - the same:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1188/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1189/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1191/

Don't know what was wrong but now it looks that all fine
