### ISSUE TITLE
Set up Foundry to use it for transactions tests

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#385]
Currently tests are disabled because API limit (more here https://github.com/status-im/status-desktop/issues/12987)

The idea was to create fake price data, but this solution could be tricky because it does not guarantee the other calculations will pass

Secondary option to deal with it is to set up Foundry https://github.com/foundry-rs/foundry :

1. set up it locally
2. try transactions with real desktop app using foundry
3. address any issues that may appear 
4. once it is stabilised, create a task for DevOps team to set up Foundry on CI
5. enable transactions tests, they should pass

Use anvil https://book.getfoundry.sh/anvil/

**Comment by glitchminer** [comment]
Installed foundry
Ran anvil `anvil --fork-url https://eth-mainnet.g.alchemy.com/v2/<your key> --fork-block-number 18963576 --fork-chain-id 1 --chain-id 1`

Built app after amending endpoints for mainnet to `http://127.0.0.1:8545/` in
- resources/default-networks.json
- src/app_service/common/network_constants.nim

Successfully added account from anvil seed phrase and transferred funds to account.
![image](https://github.com/status-im/desktop-qa-automation/assets/50769329/f1bf88b7-dfd5-42b0-a6f1-8acb1ebfd106)

When attempting to mint owner tokens 'unknown error' is shown in the UI.
![image](https://github.com/status-im/desktop-qa-automation/assets/50769329/e849d81e-f78c-4a78-a08b-d92b44212de3)


Console has an rpc error:
```
ERR 2024-01-10 12:49:00.252+00:00 error doing rpc request                    topics="rpc" tid=14239830 file=core.nim:40 methodName=wakuext_createCommunityTokenDeploymentSignature exception="\nstatus-go error [methodName:wakuext_createCommunityTokenDeploymentSignature, code:-32000, message:deployer contract not available for chainID ]\n"
```

**Comment by alaibe** [comment]
You shouldn't be offered mainnet here. By looking at the status go code:
```
package communitytokendeployer

import (
	"errors"

	"github.com/ethereum/go-ethereum/common"
)

var errorNotAvailableOnChainID = errors.New("deployer contract not available for chainID")

// addresses can be found on https://github.com/status-im/communities-contracts#deployments
var contractAddressByChainID = map[uint64]common.Address{
	5:        common.HexToAddress("0x81f4951ff8859d305F47A4574B206cF64C0d2645"), // Goerli
	420:      common.HexToAddress("0xfFa8A255D905c909379859eA45B959D090DDC2d4"), // Optimism Goerli
	421613:   common.HexToAddress("0x7Ff554af5b6624db2135E4364F416d1D397f43e6"), // Arbitrum Goerli
	11155111: common.HexToAddress("0xCDE984e57cdb88c70b53437cc694345B646371f9"), // Sepolia
	421614:   common.HexToAddress("0x7Ff554af5b6624db2135E4364F416d1D397f43e6"), // Arbitrum Sepolia
}

func ContractAddress(chainID uint64) (common.Address, error) {
	addr, exists := contractAddressByChainID[chainID]
	if !exists {
		return *new(common.Address), errorNotAvailableOnChainID
	}
	return addr, nil
}
```

This contract is not available at chain id 1
So that is a bug.

To unblock you, could you fork goerli

**Comment by glitchminer** [comment]
Thanks, it does work with Goerli.

@anastasiyaig , it just needs the amendment make to the Goerli config instead and updated fork URL
`anvil --fork-url https://eth-goerli.g.alchemy.com/v2/<your key> --fork-block-number 10352254 --fork-chain-id 5 --chain-id 5`

**Comment by Valentina1133** [comment]
During Foundry installation I faced several issues. Found a solution here - https://stackoverflow.com/questions/28124221/error-linking-with-cc-failed-exit-code-1. So if you have Apple M2 you need to set up several things more to be able to build foundry

**Comment by anastasiyaig** [comment]
we have to try that on Sepolia now because Goerli is deprecated
