### ISSUE TITLE
Run tests in qa-automation PRs on demand

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#386]
Currently we run tests per each commit in each PR for qa-automation repository. This creates additional load to our hosts we run tests on. Also, sometimes it is not needed to run tests per each commit because PR is somewhat not ready

What is needed: 

1. stop triggering tests per each commit in PRs for automation repository
2. add mechanism to trigger tests on demand (we can do that by checking PR status, lets say moving PR to 'ready for review' triggers tests launch)

**Comment by anastasiyaig** [comment]
@apentori @yakimant also not urgent but if you guys have some time, please :)

**Comment by jakubgs** [comment]
One way to achieve this would be to add the same kind of tag like we have in `status-mobile`: `no-ci-builds`

I don't think there is a way to create a PR build but not run it. At least not a built-in way in Jenkins.
One possibility is adding conditionals in the `Jenkinsfile` to simply skip all steps if it's the first run for a PR in this repo.

**Comment by anastasiyaig** [comment]
@jakubgs hey thanks for the explanation! To clarify (not really aware in details of mobile workflow now):  there could be a possibility to launch tests when a specific tag (label) is added (or removed)? If this is so - then lets do that, that could resolve my initial issue :)

**Comment by jakubgs** [comment]
If the `no-ci-builds` is added before the PR is created the job should not rune.
If it's added afterwards it should not run from then on.

Lets try it out.
