### ISSUE TITLE
UI tests: [tst_communityMessageFlows] `The user sends multiple test images with a message` verificacion scenario is broken 

### ISSUE THREAD

**Issue by noeliaSD** [status-im/desktop-qa-automation#39]
### Description
Resolve why verification is broken in the following scenario: `The user sends multiple test images with a message`

**NOTE:** When it is updated, remove the `@mayfail` tag and make sure it passes standalone but also as part of the sequence.

**Comment by Valentina1133** [comment]
Closing it, because we don't work on old squish tests anymore. Something is already automated and something will be automated in new framework
