### ISSUE TITLE
Investigate test failure in nightly (join community test)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#397]
https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/128/allure/#suites/64a2e13a8c3e80b0638402823e89ed26/f737b6d4c4705215/

**Comment by anastasiyaig** [comment]
Most likely it is related to https://github.com/status-im/status-desktop/issues/13019

**Comment by Valentina1133** [comment]
I was trying to find what is the issue, but locally it fails later on another step. Yesterday I tried to add more attempts on clicking button - it helped, but not sure that it's stable. https://github.com/status-im/desktop-qa-automation/pull/395

**Comment by anastasiyaig** [comment]
@Valentina1133 this test fails because functionality has been changed

<img width="1512" alt="Screenshot 2023-12-19 at 13 58 49" src="https://github.com/status-im/desktop-qa-automation/assets/82375995/1f85281b-5e64-4d2f-be64-ad531d463b2a">

this is new links preview

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&node-id=22347-219483&mode=design&t=7fI7PUxC0dPqeS1H-0

please fix the test according the changes, @lukaszso could assist with the questions

**Comment by anastasiyaig** [comment]
the test is now disabled in master for now, please uncomment it when fixed
