### ISSUE TITLE
[QA EPIC] Profile showcase

### ISSUE THREAD

**Issue by glitchminer** [status-im/desktop-qa-automation#399]
Desktop issue: 
https://github.com/status-im/status-desktop/issues/12984, 
https://github.com/status-im/status-desktop/issues/13069,
https://github.com/status-im/status-desktop/issues/13304

**Comment by anastasiyaig** [comment]
perhaps should be moved to 0.17 since the priority is changed

**Comment by anastasiyaig** [comment]
no qa epics anymore
