### ISSUE TITLE
UI tests: tst_ChatFlow -  Update `The user can send a sticker after installing a free pack` to be stable

### ISSUE THREAD

**Issue by noeliaSD** [status-im/desktop-qa-automation#40]
### Description

The following scenario has been disabled from CI `The user can send a sticker after installing a free pack`
 since it may be flaky due to undeterministic network conditions and 3rd party infura response.

Review how we can make it estable and enable it again in the CI.

**Comment by Valentina1133** [comment]
Closing it, because we don't work on old squish tests anymore. Something is already automated and something will be automated in new framework
