### ISSUE TITLE
Run tests in desktop PRs against the artefact from PR

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#411]
For new tests that are being launched in status-desktop PRs, lets run them against artefact from the PR, not against nightly build

**Comment by jakubgs** [comment]
I'm not sure what you mean:

>lets run them against artefact from the PR, not against nightly build

But that's what we've always been doing. For example look at the logs from this E2E run for `pr13104`:

>16:10:47  Copied 1 artifact from "[status-desktop » prs » linux » x86_64 » package » PR-13104](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/package/job/PR-13104/)" build number [9](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/package/job/PR-13104/9/)
```
17:10:49  + tar -zxvf pkg/StatusIm-Desktop-240104-155334-7b47cc-pr13104-x86_64.tar.gz -C ./aut
17:10:49  StatusIm-Desktop-240104-155334-7b47cc-pr13104-x86_64.AppImage
17:10:51  StatusIm-Desktop-240104-155334-7b47cc-pr13104-x86_64.AppImage.asc
```
https://ci.status.im/job/status-desktop/job/e2e/job/prs/1053/console

**Comment by anastasiyaig** [comment]
Ah perfect then, thanks for confirming that
