### ISSUE TITLE
UI tests: Mention test fails because of `installSignalHandler() invocation`

### ISSUE THREAD

**Issue by jrainville** [status-im/desktop-qa-automation#42]
## Description

The test `The user can do a mention` fails on step `the "<displayName>" mention with message "<message>" have been sent` with the error:

```
Detail RuntimeError: Error in installSignalHandler() invocation  /home/jonathan/dev/status-desktop/test/ui-test/src/drivers/SquishDriver.py:281

Location /home/jonathan/dev/status-desktop/test/ui-test/src/drivers/SquishDriver.py:281 
```

**Comment by Valentina1133** [comment]
Will be implemented for new framework in this task - https://github.com/status-im/desktop-qa-automation/issues/592. This one I close
