### ISSUE TITLE
UI tests: one to one test often fails on CI

### ISSUE THREAD

**Issue by jrainville** [status-im/desktop-qa-automation#43]
## Description

The test `The user can create a one to chat` often fails on CI with 
```
[Errno 2] No such file or directory: '../../../../../Status/data'
```

eg fail: https://ci.status.im/job/status-desktop/job/branches/job/e2e/job/PR-9298/5/squishResults_230127_150832.036/webreport_230127_150832.036_linux-06/index.html

Once the test is fixed, remove the `@mayfail` tag

**Comment by Valentina1133** [comment]
Close it, we have a separate task for 1x1 chat for new framework https://github.com/status-im/desktop-qa-automation/issues/592
