### ISSUE TITLE
Investigate how to use foundry in transaction automated tests

### ISSUE THREAD

**Issue by Valentina1133** [status-im/desktop-qa-automation#445]
Docs: https://book.getfoundry.sh/getting-started/installation

Set up everything (Foundry and etc.) - done

Add to CI build - created branch chore/network_configs_for_transactions and Mac build with needed configs: https://status-im-builds.ams3.digitaloceanspaces.com/StatusIm-Desktop-240117-022633-cbcee9-aarch64.dmg

Try to use it for our test and see how it works

**Comment by anastasiyaig** [comment]
we need to redo all this for Sepolia 
https://book.getfoundry.sh/getting-started/installation
