### ISSUE TITLE
Build flowchards for Keycard flows and cover it in testrail

### ISSUE THREAD

**Issue by glitchminer** [status-im/desktop-qa-automation#455]
Create diagram mapping decision points in Keycard flows 

- [ ] setup new keycard with existing account flow
    - flow diagram: https://drive.google.com/file/d/1DUSW0xMOry3ViSatrpFHe3GlIAU-l1is/view?usp=drive_link
    - test rail coverage:

**Comment by glitchminer** [comment]
Completed setup new keycard with existing account flow - scenarios to be reviewed and next flow to be started.

**Comment by anastasiyaig** [comment]
@glitchminer i changed description body a bit to reflect the achievements . Also, i think if you are comfortable with it - please share the flow chart(s) in Notion in our Requirements section

**Comment by anastasiyaig** [comment]
Moving that to 0.17 for now
