### ISSUE TITLE
Onboarding: review current test cases set

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#458]
Review test cases in https://ethstatus.testrail.net/index.php?/suites/view/5308&group_by=cases:section_id&group_order=asc&display_deleted_cases=0

Outcomes:
- list of empty, old, irrelevant test cases identified
- suggest improvements

**Comment by Michal-Status** [comment]
[Test case review.pdf](https://github.com/status-im/desktop-qa-automation/files/14038071/Test.case.review.pdf)

https://ethstatus.testrail.net/index.php?/runs/view/14505

Presentation and link to the test run
