### ISSUE TITLE
Prepare a small presentation about new tests

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#470]
Describe:
- in short how old tests were working
- why the change is needed
- where are the tests now
- how to read the allure report
- how to launch tests
- where to find a manual for local set up
- what is changing compared to old approach (running all tests VS smoke suite + nightly full regression)

**Comment by Valentina1133** [comment]
https://docs.google.com/presentation/d/1RC4VYdcJK6XtlhKd2_wj5qEvFoFI8XdEXvTxiYSOo7w/edit#slide=id.g2b49de3e0aa_1_97 - presentation

https://docs.google.com/document/d/1M2E2uEnlCsYIBM7MzueRWsn7H-HqNbnnb-05z982dnQ/edit - text

**Comment by Valentina1133** [comment]
I added one more slide with statistics of our tests for PRs and more text. @anastasiyaig Please, can you check and I will close the task if all good.

**Comment by anastasiyaig** [comment]
@Valentina1133 sure thanks for your efforts! can we just change the screenshot of PRs queue from our repo to the runs from desktop repo? https://ci.status.im/job/status-desktop/job/e2e/job/prs/
sorry about that,  i had to be more specific earlier :(

**Comment by Valentina1133** [comment]
Done! 

> @Valentina1133 sure thanks for your efforts! can we just change the screenshot of PRs queue from our repo to the runs from desktop repo? https://ci.status.im/job/status-desktop/job/e2e/job/prs/
> sorry about that, i had to be more specific earlier :(

**Comment by anastasiyaig** [comment]
perfect, we are good to go! :)
