### ISSUE TITLE
Onboarding: learn how to get test funds

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#471]
https://www.notion.so/How-to-get-test-funds-859e48b54caf40e78e88a0f2405bf5ab

goals:
1. understand what Mainnet / Test net is
2. understand what is L1 and L2 networks 
3. learn where to get funds for testing
4. get some ETH for Sepolia

**Comment by Michal-Status** [comment]
<img width="879" alt="Screenshot 2024-01-31 at 10 59 37" src="https://github.com/status-im/desktop-qa-automation/assets/155960867/ea6f34fb-9299-4e74-9392-03e378681970">

Successfully added test ETH and STT to my wallet, closing the ticket.
