### ISSUE TITLE
Community tests -> Optimisation: get rid of unnecessary app launches when possible

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#487]
Review community related tests and get rid of unnecessary app launches when possible. Other words, if we can do tests in the same community - let's do that.

Be careful so tests wont become self-dependant

**Comment by Valentina1133** [comment]
I will work on it in several PRs, will be fixed file by file to avoid too many changes in one PR and for more convenient review.

test_communities.py - https://github.com/status-im/desktop-qa-automation/pull/526
test_communities_categories.py - in progress
test_communities_channels.py
test_communities_permissions.py - already done 
test_communities_pin_and_unpin_messages.py
test_communities_screens_overview.py
test_join_community.py

**Comment by Valentina1133** [comment]
All done
