### ISSUE TITLE
Fix Account order test , it is flaky

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#519]
`test_change_account_order_by_drag_and_drop` fails without clear reason.  I can reproduce it locally but 2 out of 5 attempts.

**Comment by Valentina1133** [comment]
It is blocked by bug - https://github.com/status-im/status-desktop/issues/13836

Also I figured out what is the issue with the drag and drop itself. Sometimes we get the same coordinates for first and second account, so that's why nothing happens. We need to figure out now why it's happening
