### ISSUE TITLE
1x1 chat: can send reply, emoji, edit, save and delete own message, cannot delete others messages

### ISSUE THREAD

**Issue by Valentina1133** [status-im/desktop-qa-automation#592]
Use activity center for contact requests

I think it's better to split it to several tasks, because it's already too long scenario

Here - can send reply, emoji, edit, save and delete own message, add reaction

Next tasks:
Send sticker
Send image
Send link
Mention
Can mark a chat as read
Can clean chat history
Add reaction

https://github.com/status-im/desktop-qa-automation/issues/281

**Comment by anastasiyaig** [comment]
@Valentina1133 please close either this task, or https://github.com/status-im/desktop-qa-automation/issues/601. (merge them into 1)

**Comment by Valentina1133** [comment]
Closing this one, because it was automated before my vacation. And for the rest another task was created.
