### ISSUE TITLE
UI tests: Activity View -> Can copy details of transaction with right click and from transaction details page

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#61]
CTA
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=12304-276234&t=FrGo7aFKkwF5hBMF-4

Same actions in context menu
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=12479-292438&t=FrGo7aFKkwF5hBMF-4

**Comment by Valentina1133** [comment]
I started working on this one, but the problem is that it often fails before sending transaction. I will try to get back to it later or maybe even better after foundry will be set up for our tests
