### ISSUE TITLE
market data scenario

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#649]
Add a test that will check that the prices and chart are not empty (or integrate to any existing test)

**Comment by Valentina1133** [comment]
I investigated how to implement it. With prices - no problem, we can get it from every single box with text.
But there is the problem with charts. I compared locators for empty and non empty chart and they are completely the same

scrollView_graphComponent_Chart = {"container": scrollView_StatusScrollView, "id": "graphComponent", "type": "Chart", "unnamed": 1, "visible": True}

I also checked the properties for both - couldn't find any differences between them. So we need to figure out how to get this info.

**Comment by Valentina1133** [comment]
Ok. I found (but not sure yet), that there are different values of property maxTicksLimit if there is a graph (if not - the value is 0), maybe we can check this property to make sure that there is a graph

**Comment by anastasiyaig** [comment]
@Valentina1133 well if we get prices (they are not none / null) then we can skip checking the curve line of the chart, having data in prices field is the main idea

**Comment by Valentina1133** [comment]
@anastasiyaig Ok! Great then
