### ISSUE TITLE
UI tests: improve keycard settings test

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#88]
1. move existing test from `tst_wallet_accountsManagement` to `tst_wallet_settingsManagement`
2. rework the `Then settings keycard section is opened` step to check the object (class) of the dedicated settings page (add a keycard class in `SettingsScreen.py`)

<img width="1840" alt="Screenshot 2023-08-15 at 16 05 03" src="https://github.com/status-im/desktop-qa-automation/assets/82375995/63a5b8ee-395c-436e-88f3-74bc74f78aa4">

**Comment by Valentina1133** [comment]
Closing it because was automated in new framework and merged
